# -*- coding: utf-8 -*-
"""feature_selection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WiWNVmu653kecYMHnqtshCUd8lgW3qQl
"""

import os

# Always resolve to project root
BASE_PATH = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


import numpy as np
import pandas as pd
import json
from sklearn.feature_selection import VarianceThreshold

def feature_selection(X_train, features, base_path, corr_threshold=0.97):
    """
    Perform variance thresholding + correlation-based pruning.
    Save list of selected features as JSON.
    """

    df = pd.DataFrame(X_train, columns=features)

    print(f"Features before selection: {len(features)}")  # ← Add here

    # 🔹 1. Variance Threshold
    vt = VarianceThreshold()
    X_vt = vt.fit_transform(df)
    kept_after_vt = df.columns[vt.get_support()].tolist()

    print(f"Features after variance threshold: {len(kept_after_vt)}")  # ← Add here

    df_vt = df[kept_after_vt]

    # 🔹 2. Correlation Filtering
    corr = df_vt.corr().abs()
    upper = corr.where(np.triu(np.ones(corr.shape), k=1).astype(bool))

    to_drop = [col for col in upper.columns if any(upper[col] > corr_threshold)]
    final_features = [f for f in kept_after_vt if f not in to_drop]

    print(f"Features after correlation filtering: {len(final_features)}")  # ← Add here

    # 🔹 Save selected feature names
    model_dir = os.path.join(base_path, "Spark")
    os.makedirs(model_dir, exist_ok=True)

    with open(os.path.join(model_dir, "selected_features.json"), "w") as f:
        json.dump(final_features, f, indent=4)

    return final_features



