# -*- coding: utf-8 -*-
"""preprocess.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17w674jcPBR4vhts12HXji_ZHoHu1lpxd
"""
import os

# Always resolve to project root
BASE_PATH = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
import joblib


def clean_dataset(df):
    """Replace inf values, remove NaN using column median."""
    df = df.copy()
    df.replace([np.inf, -np.inf], np.nan, inplace=True)
    df.fillna(df.median(), inplace=True)
    return df

def preprocess(train, val, test, base_path):
    """
    Clean dataset, keep only benign training samples (unsupervised),
    scale using StandardScaler (saved for Spark).
    """

    # 🔹 Keep only benign samples in training set
    train = train[train["label"] == "BenignTraffic"].reset_index(drop=True)

    # 🔹 Remove label column
    features = [c for c in train.columns if c != "label"]

    # 🔹 Clean numeric data
    X_train = clean_dataset(train[features])
    X_val   = clean_dataset(val[features])
    X_test  = clean_dataset(test[features])

    # 🔹 Fit StandardScaler on train only
    scaler = StandardScaler()
    X_train_s = scaler.fit_transform(X_train)
    X_val_s   = scaler.transform(X_val)
    X_test_s  = scaler.transform(X_test)

    # 🔹 Save scaler for Spark
    model_dir = os.path.join(base_path, "Spark")
    os.makedirs(model_dir, exist_ok=True)
    joblib.dump(scaler, os.path.join(model_dir, "scaler.pkl"))

    return X_train_s, X_val_s, X_test_s, features


if __name__ == "__main__":
    from Spark.dataset_loader import load_splits
    from Spark.preprocess import preprocess
    import os

    BASE_PATH = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    train, val, test = load_splits(BASE_PATH)
    X_train_s, X_val_s, X_test_s, features = preprocess(train, val, test, BASE_PATH)

    print("✅ Preprocessing done!")
    print(f"X_train_s shape: {X_train_s.shape}")
    print(f"X_val_s shape:   {X_val_s.shape}")
    print(f"X_test_s shape:  {X_test_s.shape}")
