# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X3Eqg2fIIz9oXFbWov8Jqy_7gr04GXAp
"""

import os

# Always resolve to project root
BASE_PATH = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM, RepeatVector, TimeDistributed, Dense

def build_lstm_autoencoder(n_features):
    """
    Simple LSTM Autoencoder for tabular anomaly detection.
    """

    inputs = Input(shape=(1, n_features))

    # 🔹 Encoder
    x = LSTM(64, return_sequences=False)(inputs)
    encoded = Dense(32, activation="relu")(x)

    # 🔹 Decoder
    x = RepeatVector(1)(encoded)
    x = LSTM(64, return_sequences=True)(x)
    outputs = TimeDistributed(Dense(n_features))(x)

    model = Model(inputs, outputs)
    model.compile(optimizer="adam", loss="mse")

    return model


