# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.
"""

import os
import numpy as np
from .LSTMAE_model import build_lstm_autoencoder


# Always resolve to project root
BASE_PATH = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def train_autoencoder(X_train, X_val, base_path, n_features, epochs=10, batch_size=512):
    """
    Train LSTM autoencoder and save the final model.
    """

    # Reshape inputs for LSTM: (samples, timesteps, features)
    X_train_lstm = np.expand_dims(X_train, axis=1)
    X_val_lstm   = np.expand_dims(X_val, axis=1)

    # Build model
    model = build_lstm_autoencoder(n_features)

    # Train
    history = model.fit(
        X_train_lstm, X_train_lstm,
        validation_data=(X_val_lstm, X_val_lstm),
        epochs=epochs,
        batch_size=batch_size
    )

    # Save model
    model_dir = os.path.join(base_path, "Models")
    os.makedirs(model_dir, exist_ok=True)
    model.save(os.path.join(model_dir, "lstm_autoencoder.h5"))

    return history, model

print("Model import OK!")


